### ISSUE TITLE
More than one port (4326 AND 4327)

### ISSUE THREAD

**Issue by klavavaski** [lacaulac/rcon-web-admin#29]
Please consider making it easier to adjust the requisite ports that the web server and subsequent applets run on. 4326 is default for the webserver itself, but 4327 is default for the frontend and backend.

Had a real hell of a time figuring out why I was only getting partial functionality. Turns out it's because I only allowed one of the two ports through the firewall!

Additionally, modifying config.template.js post-install is irrelevant, since post-install the port config is in ./src/config.js

**Comment by chylex** [comment]
Why are two ports even needed? I'm running other applications on my server that also use websockets, and they have no problems running on a single port. Would be nice RCON Web Admin could work with a single port too.

**Comment by Bazimek** [comment]
Oh my god! Thank you!

**Comment by jaguardev** [comment]
if it makes sense, you can set RWA_WEBSOCKET_URL to soimehting like "/ws" and then do a "routing" on some frontend, i.e nginx

just for instance, ingress might look like this:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mc-rcon
  namespace: minecraft-server
spec:
  ingressClassName: public
  rules:
    - host: rcon.mc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mc-rcon
                port: { number: 4326 }
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: mc-rcon
                port: { number: 4327 }
```
