### ISSUE TITLE
Access the Service via ingress and traefik

### ISSUE THREAD

**Issue by peterchen19** [lacaulac/rcon-web-admin#36]
I'm trying to get the service running via Ingress and traefik but nothing seems too work. Q1 is it even supportet Q2 If not, will it be?

**Comment by fossum** [comment]
Same. I've got access to the site, but no page fully loads. I'm guessing 4326 is hard-coded somewhere, because all pages just sit at the loading dots. I've attached my stack for reference.

```yaml
version: "3.7"

services:
  web:
    image: itzg/rcon:latest
    volumes:
    - database:/opt/rcon-web-admin/db
    environment:
    - RWA_PASSWORD=MyPass
    deploy:
      labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.rcon.rule=Host(`rcon.my.domain`)
      - traefik.http.routers.rcon.tls=true
      - traefik.http.routers.rcon.tls.certresolver=le
      - traefik.http.services.rcon.loadbalancer.server.port=4326
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 1200s
      placement:
        constraints:
          - node.role==manager
    networks:
      - traefik-public

volumes:
  database:

networks:
  traefik-public:
    external: true
    name: traefik-public
```
